### PR TITLE
GSGGR-155 Add OpenID authentication support for Geoshop Backend

### PR DESCRIPTION
**Pull request by lanseg**
Now it is possible to authenticate in the Geoshop backend using Zitadel's OpenID. 
Current statie:

- Login and logout with new authentication method: OpenID / Zitadel, previous method
- Regular Login/Password authentication still works
- Permission mapping for main roles: admin (superuser) and staff (staff)
- Token authentication (e.g. for Extract) still works

To be added:

- Unified mapping between Zitadel roles and Geoshop group memberships
- Share authentication code between backend and frontend
- End-to-end tests for backend/frontend and testing Zitadel server

### CODE REVIEW

**Comment by lanseg** [comment]
> Hi @lanseg thanks for this! I was able to follow the tutorial until the creation of the app but I'm a little stuck after. What "kind of app" did you create on Zitadel? PKCE?

Web application / Code (PKCE would be also worth checking). Main problem I had was because Zitadel removes trailing slash in redirect links, but default urls.py from Mozilla OIDC have them and require them.
Also, the tutorial doesn't say about importance of a small checkbox "Assert Roles on Authentication"

**Comment by maltaesousa** [comment]
Thanks a lot, it works! Thanks for the job

**Review by maltaesousa — APPROVED** [review]
If you want, maybe add it to the doc it's an Web / Code app in Zitadel that we should configure

**Comment by lanseg** [comment]
> If you want, maybe add it to the doc it's an Web / Code app in Zitadel that we should configure

Ok, I'll extend this chapter in the README file. Also, thanks for noticing PKCE question, adding support will require some work too.

**Pull request merged**
