### PR TITLE
API Documentation

### PR DESCRIPTION
**Pull request by marionb**
NOTE
- The API documentation can currently be found under http://localhost:8000/api/docs/ 
- you need to apply the DB migrations for this to run. See the README

@maltaesousa I had to make some changes in the tests but only because the name of the attribute changed. The logic of the teat is still the same.

### CODE REVIEW

**Comment by marionb** [comment]
> Thanks for this PR! Can you please add drf-spectacular to requirements.txt before merging?

@maltaesousa I regenerated the `requirements.txt` but it removes the information about the python version on some of the packages. do you need that?

**Comment by maltaesousa** [comment]
@marionb Yes, those information are important for the build. With the new requirements.txt, the build of the docker image gets broken. You can test it with `docker build -t sitn/geoshop-dev-api --build-arg ENV_FILE=.env.local .`

**Comment by marionb** [comment]
OK thanks I will take a look and re-add that. 
by the way what tool are you using to generate the requremens.txt in that way?

**Comment by maltaesousa** [comment]
When I started that in 2019, I was using pipenv which I thought it was a great tool. It turned out to not be as good as I thought. So If you have any suggestions, I'll be happy to switch :)
Maybe we should update the Docker base image to something closer to what you use at camptocamp so we can use your tools?

**Comment by danduk82** [comment]
@maltaesousa I suggest that we move to `poetry` and setup a `pyproject.toml` . I'll have a look with @marionb on monday

**Comment by danduk82** [comment]
@maltaesousa I think the python builder should be a separate issue/PR. I have created one here https://github.com/camptocamp/geoshop-back/issues/17

**Comment by maltaesousa** [comment]
Agree so is it ok to just change the requirements manually to add this `drf-spectacular==0.27.1` so it doesn't break the build and  migrate to poetry in another PR?

**Comment by marionb** [comment]
@maltaesousa 
Yes, If it is OK for you I will merge this now.
I added the package to the existing `requirements.txt` and we will add the poetry in another PR.

**Pull request merged**
